language: cpp
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libeigen3-dev
before_script:
  - mkdir build
  - cd build
  - cmake -DOPENMP=OFF -DCMAKE_INSTALL_PREFIX=/usr .. 
script: 
  - make && make test && sudo make install
after_success:
  - cd ..
  - cd examples
  - ${CXX} -std=c++0x -I/usr/include/eigen3 standalone_example.cpp -lspii
  - ./a.out
